### ISSUE TITLE
slow performance with lots of Requires: statements

### ISSUE THREAD

**Issue by devjgm** [pkgconf/pkgconf#229]
When upgrading my (C++) project to gRPC 1.39.0 (the latest), I discovered that Fedora's `pkgconf` seems to be slow when `.pc` files have many `Requires:` clauses. The issue from my project is https://github.com/googleapis/google-cloud-cpp/issues/7052 and it has some additional context. We worked around this problem by installing and using https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz instead.

It is possible that we're doing something wrong, in which case I'd be happy to learn what it is so we can fix it. Otherwise, I'm reporting this issue in case it can be fixed in a future version of pkgconf/fedora.

## Steps to reproduce

1. Download the [pkgconfig-files.tar.gz](https://github.com/pkgconf/pkgconf/files/6886662/pkgconfig-files.tar.gz) tarball, which contains all the `*.pc` files from a fully installed copy of `google-cloud-cpp`, `protobuf`, `grpc`, `abseil`, `openssl`, etc. This tarball does NOT contain the compiled artifacts -- only the .pc files. This is just so that we can use `pkg-config` in a docker container to reproduce the problem.
2. Start a new docker container w/ the above tarball mounted so that the files can be extracted into `/tmp` in the image.
```console
$ docker run --rm -it --volume=$PWD/pkgconfig-files.tar.gz:/tarball fedora:34 bash
```
3. Within the running container, extract the tarball into `/tmp`, which will put all the `.pc` files in a single directory
```console
[root@b1cac6cb716c /]# tar -C /tmp -zxvf /tarball
...
[root@b1cac6cb716c /]# export PKG_CONFIG_PATH=/tmp/pkgconfig-files
```
4. Install `pkg-config`
```console
[root@b1cac6cb716c /]# dnf install -y pkgconfig
``` 
5. See how slow `pkg-config` is for certain packages that contain a lot of `Requires:` statements.
```console
[root@b1cac6cb716c /]# time pkg-config google_cloud_cpp_grpc_utils --libs-only-l --static
...
real    0m3.184s
user    0m3.155s
sys     0m0.028s
```

The above is over 3 seconds. Invoked repeatedly in our actual CI builds this adds up to over an hour of time spent in `pkg-config`. When we switched our builds to https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz  (https://github.com/googleapis/google-cloud-cpp/pull/7061), each invocation completes in a small fraction of a second.

## Additional info

I don't know about the internals of pkg-config, so I don't really know what it's doing or supposed to do, but I'll say that the `--debug` flag produces some interesting output.

```console
[root@b1cac6cb716c /]# pkg-config google_cloud_cpp_grpc_utils --debug 2>&1 | grep -Po '\[pkgconf.+\]' | sort | uniq -c | sort -n
...
     69 [pkgconf_fragment_parse]: post-subst: [-I${includedir} -DNOMINMAX] -> [-I/usr/local/include -DNOMINMAX]
     90 [pkgconf_cache_add]
     90 [pkgconf_cache_remove]
    180 [pkgconf_pkg_try_specific_path]
    309 [pkgconf_fragment_add]
    393 [pkgconf_cache_lookup]
    452 [pkgconf_tuple_add]
    696 [pkgconf_pkg_find]
 458241 [pkgconf_pkg_ref]
 458241 [pkgconf_pkg_unref]
 915123 [pkgconf_pkg_verify_dependency]
 915518 [pkgconf_pkg_traverse]
```

**Comment by kaniini** [comment]
Hi, sorry, I have not noticed this issue until now.  For some reason, GitHub does not reliably send bug mail to me for pkgconf anymore.

The `pkgconf_pkg_ref/pkgconf_pkg_unref` being so high is quite strange.

**Comment by kaniini** [comment]
The issue is that the dependency solver is being invoked thousands of times (e.g. for each subgraph).  A probable solution would be to track dependency nodes that are already part of a proposed solution and reusing them for future resolutions.

**Comment by kaniini** [comment]
The solver, incidentally, is solving for `absl_config` frequently.  Likely that is the deepest point in the graph.  I tried to render it with GraphViz but it crashed, haha

**Comment by coryan** [comment]
Any more thoughts on how to fix this?  Or maybe some hints on what needs fixing so I can try to send you a PR?

**Comment by kaniini** [comment]
Basically we need to track what nodes have been visited already, which I have a branch somewhere that does this using serial numbers.  Problem is that I haven’t had time to figure out the test failures!

**Comment by kaniini** [comment]
Fixed by new dependency-flattening solver.

**Comment by coryan** [comment]
Thank you so much, this is really great news.

**Comment by coryan** [comment]
Do you recall which version included these fixes?   I am seeing the same slow performance on version 1.8.1, the release included with Debian 12 (Bookworm).

**Comment by mattst88** [comment]
Looks like it should be in 1.9.0 according to the `NEWS` entry:

```
Changes from 1.8.0 to 1.9.0:
----------------------------                                               
                                                                    
* pkgconf 1.9.0 is the first testing release in the pkgconf 2.0 development
  series.  While it is believed to be suitable for production, there may be
  bugs due to the overall redesign of the solver and other initiatives.
  Additionally, a future release of pkgconf plans will have additional ABI
  breaks for the libpkgconf library before the pkgconf 2.0 release is cut.
                            
* There is now a new solver that is designed to provide higher performance
  with complicated graphs, which works by flattening the dependency graph
  into a smaller set of dependencies.  This graph can then be evaluated
  instead of the original dependency graph without having to visit every
  edge in the graph.
                                                                   
  NOTE: This solver, while providing significant performance improvements,
  does so, at the cost of changed behavior for some edge cases (such as
  circular dependencies).
```

**Comment by coryan** [comment]
Hmm... the problem persists until at least 2.1.0:

```
pkgconf --version
2.1.0

time env PKG_CONFIG_PATH=$PWD/repro-pkgconf pkgconf --libs google_cloud_cpp_bigquery

-L/workspace/repro-pkgconf/../../lib64 -lgoogle_cloud_cpp_bigquery -lgoogle_cloud_cpp_grpc_utils -lgoogle_cloud_cpp_common -L/usr/lib64 -labsl_bad_any_cast_impl -lgoogle_cloud_cpp_iam_credentials_v1_iamcredentials_protos -lgoogle_cloud_cpp_iam_credentials_v1_common_protos -lgoogle_cloud_cpp_bigquery_protos -lgoogle_cloud_cpp_api_distribution_protos -lgoogle_cloud_cpp_api_metric_protos -lgoogle_cloud_cpp_api_label_protos -lgoogle_cloud_cpp_iam_v1_iam_policy_protos -lgoogle_cloud_cpp_api_field_behavior_protos -lgoogle_cloud_cpp_api_resource_protos -lgoogle_cloud_cpp_iam_v1_options_protos -lgoogle_cloud_cpp_iam_v1_policy_protos -lgoogle_cloud_cpp_longrunning_operations_protos -lgoogle_cloud_cpp_api_annotations_protos -lgoogle_cloud_cpp_api_http_protos -lgoogle_cloud_cpp_api_client_protos -lgoogle_cloud_cpp_api_launch_stage_protos -lgoogle_cloud_cpp_rpc_status_protos -lgoogle_cloud_cpp_rpc_error_details_protos -lgoogle_cloud_cpp_type_expr_protos -lgrpc++ -lgrpc -laddress_sorting -lre2 -lupb -lgpr -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_hash -labsl_city -labsl_low_level_hash -labsl_random_distributions -labsl_random_seed_sequences -labsl_random_internal_pool_urbg -labsl_random_internal_randen -labsl_random_internal_randen_hwaes -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen_slow -labsl_random_internal_platform -labsl_random_internal_seed_material -labsl_random_seed_gen_exception -labsl_statusor -labsl_status -labsl_cord -labsl_cordz_info -labsl_cord_internal -labsl_cordz_functions -labsl_exponential_biased -labsl_cordz_handle -labsl_crc_cord_state -labsl_crc32c -labsl_crc_internal -labsl_crc_cpu_detect -labsl_bad_optional_access -labsl_strerror -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_kernel_timeout_internal -labsl_stacktrace -labsl_symbolize -labsl_debugging_internal -labsl_demangle_internal -labsl_malloc_internal -labsl_time -labsl_civil_time -labsl_strings -labsl_string_view -labsl_strings_internal -labsl_base -lrt -labsl_spinlock_wait -labsl_int128 -labsl_throw_delegate -labsl_time_zone -labsl_bad_variant_access -labsl_raw_logging_internal -labsl_log_severity -lssl -lcrypto -lprotobuf -lz -lcares

real    2m55.785s
user    2m51.841s
sys     0m3.932s
```


[repro-pkgconf-229.tar.gz](https://github.com/pkgconf/pkgconf/files/13745654/repro-pkgconf-229.tar.gz)

PS: I understand development has moved to https://gitea.treehouse.systems/ariadne/pkgconf/ but I am still trying to create an account there.

**Comment by qazwsxedcrfvtg14** [comment]
I create a PR, that might be able to resolve the issue:
https://github.com/pkgconf/pkgconf/pull/339

**Comment by kaniini** [comment]
Should be fixed in pending 2.1.1 with a slightly modified version of the PR in #339.
